# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_theta <- function(y, mu, dfr, limit, eps) {
    .Call(`_spacrt_estimate_theta`, y, mu, dfr, limit, eps)
}

